import { PlayerFonts } from "../typings";

export async function getFonts(): Promise<PlayerFonts> {
  return {
    families: {
      inter: {
        name: "Inter",
        sizeFactor: 1,
        styles: [
          {
            name: "Thin",
            style: "normal",
            weight: "100",
            url: await import("./inter/Inter-Thin.woff2"),
          },
          {
            name: "Thin Italic",
            style: "italic",
            weight: "100",
            url: await import("./inter/Inter-ThinItalic.woff2"),
          },
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./inter/Inter-ExtraLight.woff2"),
          },
          {
            name: "Extra Light Italic",
            style: "italic",
            weight: "200",
            url: await import("./inter/Inter-ExtraLightItalic.woff2"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./inter/Inter-Light.woff2"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./inter/Inter-LightItalic.woff2"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./inter/Inter-Regular.woff2"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./inter/Inter-Italic.woff2"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./inter/Inter-Medium.woff2"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./inter/Inter-MediumItalic.woff2"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./inter/Inter-SemiBold.woff2"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./inter/Inter-SemiBoldItalic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./inter/Inter-Bold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./inter/Inter-BoldItalic.woff2"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./inter/Inter-ExtraBold.woff2"),
          },
          {
            name: "Extra Bold Italic",
            style: "italic",
            weight: "800",
            url: await import("./inter/Inter-ExtraBoldItalic.woff2"),
          },
          {
            name: "Black",
            style: "normal",
            weight: "900",
            url: await import("./inter/Inter-Black.woff2"),
          },
          {
            name: "Black Italic",
            style: "italic",
            weight: "900",
            url: await import("./inter/Inter-BlackItalic.woff2"),
          },
        ],
      },
      interDisplay: {
        name: "Inter Display",
        sizeFactor: 1,
        styles: [
          {
            name: "Thin",
            style: "normal",
            weight: "100",
            url: await import("./inter/InterDisplay-Thin.woff2"),
          },
          {
            name: "Thin Italic",
            style: "italic",
            weight: "100",
            url: await import("./inter/InterDisplay-ThinItalic.woff2"),
          },
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./inter/InterDisplay-ExtraLight.woff2"),
          },
          {
            name: "Extra Light Italic",
            style: "italic",
            weight: "200",
            url: await import("./inter/InterDisplay-ExtraLightItalic.woff2"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./inter/InterDisplay-Light.woff2"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./inter/InterDisplay-LightItalic.woff2"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./inter/InterDisplay-Regular.woff2"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./inter/InterDisplay-Italic.woff2"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./inter/InterDisplay-Medium.woff2"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./inter/InterDisplay-MediumItalic.woff2"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./inter/InterDisplay-SemiBold.woff2"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./inter/InterDisplay-SemiBoldItalic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./inter/InterDisplay-Bold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./inter/InterDisplay-BoldItalic.woff2"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./inter/InterDisplay-ExtraBold.woff2"),
          },
          {
            name: "Extra Bold Italic",
            style: "italic",
            weight: "800",
            url: await import("./inter/InterDisplay-ExtraBoldItalic.woff2"),
          },
          {
            name: "Black",
            style: "normal",
            weight: "900",
            url: await import("./inter/InterDisplay-Black.woff2"),
          },
          {
            name: "Black Italic",
            style: "italic",
            weight: "900",
            url: await import("./inter/InterDisplay-BlackItalic.woff2"),
          },
        ],
      },
      nebulaSans: {
        name: "Nebula Sans",
        sizeFactor: 1,
        styles: [
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./nebula-sans/NebulaSans-Light.woff2"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./nebula-sans/NebulaSans-LightItalic.woff2"),
          },
          {
            name: "Book",
            style: "normal",
            weight: "400",
            url: await import("./nebula-sans/NebulaSans-Book.woff2"),
          },
          {
            name: "Book Italic",
            style: "italic",
            weight: "400",
            url: await import("./nebula-sans/NebulaSans-BookItalic.woff2"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./nebula-sans/NebulaSans-Medium.woff2"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./nebula-sans/NebulaSans-MediumItalic.woff2"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./nebula-sans/NebulaSans-Semibold.woff2"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./nebula-sans/NebulaSans-SemiboldItalic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./nebula-sans/NebulaSans-Bold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./nebula-sans/NebulaSans-BoldItalic.woff2"),
          },
          {
            name: "Black",
            style: "normal",
            weight: "800",
            url: await import("./nebula-sans/NebulaSans-Black.woff2"),
          },
          {
            name: "Black Italic",
            style: "italic",
            weight: "800",
            url: await import("./nebula-sans/NebulaSans-BlackItalic.woff2"),
          },
        ],
      },
      literataText: {
        name: "Literata Text",
        sizeFactor: 1.05,
        styles: [
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./literata/LiterataTT-TextLight.woff2"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./literata/LiterataTT-TextLightItalic.woff2"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./literata/LiterataTT-TextRegular.woff2"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./literata/LiterataTT-TextItalic.woff2"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./literata/LiterataTT-TextMedium.woff2"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./literata/LiterataTT-TextMediumItalic.woff2"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./literata/LiterataTT-TextSemibold.woff2"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./literata/LiterataTT-TextSemiboldItalic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./literata/LiterataTT-TextBold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./literata/LiterataTT-TextBoldItalic.woff2"),
          },
        ],
      },
      alegreya: {
        name: "Alegreya",
        sizeFactor: 1.05,
        styles: [
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./alegreya/Alegreya-Regular.woff2"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./alegreya/Alegreya-Italic.woff2"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./alegreya/Alegreya-Medium.woff2"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./alegreya/Alegreya-MediumItalic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./alegreya/Alegreya-Bold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./alegreya/Alegreya-BoldItalic.woff2"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./alegreya/Alegreya-ExtraBold.woff2"),
          },
          {
            name: "Extra Bold Italic",
            style: "italic",
            weight: "800",
            url: await import("./alegreya/Alegreya-ExtraBoldItalic.woff2"),
          },
          {
            name: "Black",
            style: "normal",
            weight: "900",
            url: await import("./alegreya/Alegreya-Black.woff2"),
          },
          {
            name: "Black Italic",
            style: "italic",
            weight: "900",
            url: await import("./alegreya/Alegreya-BlackItalic.woff2"),
          },
        ],
      },
      charter: {
        name: "Charter",
        sizeFactor: 1,
        styles: [
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./charter/Charter-Regular.woff2"),
          },
          {
            name: "Italic",
            style: "italic",
            weight: "400",
            url: await import("./charter/Charter-Italic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./charter/Charter-Bold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./charter/Charter-BoldItalic.woff2"),
          },
        ],
      },
      ibmPlexSans: {
        name: "IBM Plex Sans",
        sizeFactor: 1,
        styles: [
          {
            name: "Thin",
            style: "normal",
            weight: "100",
            url: await import("./ibm-plex-sans/IBMPlexSans-Thin.woff2"),
          },
          {
            name: "Thin Italic",
            style: "italic",
            weight: "100",
            url: await import("./ibm-plex-sans/IBMPlexSans-ThinItalic.woff2"),
          },
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./ibm-plex-sans/IBMPlexSans-ExtraLight.woff2"),
          },
          {
            name: "Extra Light Italic",
            style: "italic",
            weight: "200",
            url: await import("./ibm-plex-sans/IBMPlexSans-ExtraLightItalic.woff2"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./ibm-plex-sans/IBMPlexSans-Light.woff2"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./ibm-plex-sans/IBMPlexSans-LightItalic.woff2"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./ibm-plex-sans/IBMPlexSans-Regular.woff2"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./ibm-plex-sans/IBMPlexSans-Italic.woff2"),
          },
          {
            name: "Text",
            style: "normal",
            weight: "450",
            url: await import("./ibm-plex-sans/IBMPlexSans-Text.woff2"),
          },
          {
            name: "Text Italic",
            style: "italic",
            weight: "450",
            url: await import("./ibm-plex-sans/IBMPlexSans-TextItalic.woff2"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./ibm-plex-sans/IBMPlexSans-Medium.woff2"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./ibm-plex-sans/IBMPlexSans-MediumItalic.woff2"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./ibm-plex-sans/IBMPlexSans-SemiBold.woff2"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./ibm-plex-sans/IBMPlexSans-SemiBoldItalic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./ibm-plex-sans/IBMPlexSans-Bold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./ibm-plex-sans/IBMPlexSans-BoldItalic.woff2"),
          },
        ],
      },
      ibmPlexSerif: {
        name: "IBM Plex Serif",
        sizeFactor: 1,
        styles: [
          {
            name: "Thin",
            style: "normal",
            weight: "100",
            url: await import("./ibm-plex-serif/IBMPlexSerif-Thin.woff2"),
          },
          {
            name: "Thin Italic",
            style: "italic",
            weight: "100",
            url: await import("./ibm-plex-serif/IBMPlexSerif-ThinItalic.woff2"),
          },
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./ibm-plex-serif/IBMPlexSerif-ExtraLight.woff2"),
          },
          {
            name: "Extra Light Italic",
            style: "italic",
            weight: "200",
            url: await import("./ibm-plex-serif/IBMPlexSerif-ExtraLightItalic.woff2"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./ibm-plex-serif/IBMPlexSerif-Light.woff2"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./ibm-plex-serif/IBMPlexSerif-LightItalic.woff2"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./ibm-plex-serif/IBMPlexSerif-Regular.woff2"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./ibm-plex-serif/IBMPlexSerif-Italic.woff2"),
          },
          {
            name: "Text",
            style: "normal",
            weight: "450",
            url: await import("./ibm-plex-serif/IBMPlexSerif-Text.woff2"),
          },
          {
            name: "Text Italic",
            style: "italic",
            weight: "450",
            url: await import("./ibm-plex-serif/IBMPlexSerif-TextItalic.woff2"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./ibm-plex-serif/IBMPlexSerif-Medium.woff2"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./ibm-plex-serif/IBMPlexSerif-MediumItalic.woff2"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./ibm-plex-serif/IBMPlexSerif-SemiBold.woff2"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./ibm-plex-serif/IBMPlexSerif-SemiBoldItalic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./ibm-plex-serif/IBMPlexSerif-Bold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./ibm-plex-serif/IBMPlexSerif-BoldItalic.woff2"),
          },
        ],
      },
      ebGaramond: {
        name: "EB Garamond",
        sizeFactor: 1.12,
        styles: [
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./eb-garamond/EBGaramond-Regular.ttf"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./eb-garamond/EBGaramond-Italic.ttf"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./eb-garamond/EBGaramond-Medium.ttf"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./eb-garamond/EBGaramond-MediumItalic.ttf"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./eb-garamond/EBGaramond-SemiBold.ttf"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./eb-garamond/EBGaramond-SemiBoldItalic.ttf"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./eb-garamond/EBGaramond-Bold.ttf"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./eb-garamond/EBGaramond-BoldItalic.ttf"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./eb-garamond/EBGaramond-ExtraBold.ttf"),
          },
          {
            name: "Extra Bold Italic",
            style: "italic",
            weight: "800",
            url: await import("./eb-garamond/EBGaramond-ExtraBoldItalic.ttf"),
          },
        ],
      },
      newsreader6pt: {
        name: "Newsreader 6pt",
        sizeFactor: 0.9,
        styles: [
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./newsreader/Newsreader6pt-ExtraLight.woff2"),
          },
          {
            name: "Extra Light Italic",
            style: "italic",
            weight: "200",
            url: await import("./newsreader/Newsreader6pt-ExtraLightItalic.woff2"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./newsreader/Newsreader6pt-Light.woff2"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./newsreader/Newsreader6pt-LightItalic.woff2"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./newsreader/Newsreader6pt-Regular.woff2"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./newsreader/Newsreader6pt-Italic.woff2"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./newsreader/Newsreader6pt-Medium.woff2"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./newsreader/Newsreader6pt-MediumItalic.woff2"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./newsreader/Newsreader6pt-SemiBold.woff2"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./newsreader/Newsreader6pt-SemiBoldItalic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./newsreader/Newsreader6pt-Bold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./newsreader/Newsreader6pt-BoldItalic.woff2"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./newsreader/Newsreader6pt-ExtraBold.woff2"),
          },
          {
            name: "Extra Bold Italic",
            style: "italic",
            weight: "800",
            url: await import("./newsreader/Newsreader6pt-ExtraBoldItalic.woff2"),
          },
        ],
      },
      newsreader16pt: {
        name: "Newsreader 16pt",
        sizeFactor: 1.05,
        styles: [
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./newsreader/Newsreader16pt-ExtraLight.woff2"),
          },
          {
            name: "Extra Light Italic",
            style: "italic",
            weight: "200",
            url: await import("./newsreader/Newsreader16pt-ExtraLightItalic.woff2"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./newsreader/Newsreader16pt-Light.woff2"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./newsreader/Newsreader16pt-LightItalic.woff2"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./newsreader/Newsreader16pt-Regular.woff2"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./newsreader/Newsreader16pt-Italic.woff2"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./newsreader/Newsreader16pt-Medium.woff2"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./newsreader/Newsreader16pt-MediumItalic.woff2"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./newsreader/Newsreader16pt-SemiBold.woff2"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./newsreader/Newsreader16pt-SemiBoldItalic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./newsreader/Newsreader16pt-Bold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./newsreader/Newsreader16pt-BoldItalic.woff2"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./newsreader/Newsreader16pt-ExtraBold.woff2"),
          },
          {
            name: "Extra Bold Italic",
            style: "italic",
            weight: "800",
            url: await import("./newsreader/Newsreader16pt-ExtraBoldItalic.woff2"),
          },
        ],
      },
      newsreader72pt: {
        name: "Newsreader 72pt",
        sizeFactor: 1.02,
        styles: [
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./newsreader/Newsreader72pt-ExtraLight.woff2"),
          },
          {
            name: "Extra Light Italic",
            style: "italic",
            weight: "200",
            url: await import("./newsreader/Newsreader72pt-ExtraLightItalic.woff2"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./newsreader/Newsreader72pt-Light.woff2"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./newsreader/Newsreader72pt-LightItalic.woff2"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./newsreader/Newsreader72pt-Regular.woff2"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./newsreader/Newsreader72pt-Italic.woff2"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./newsreader/Newsreader72pt-Medium.woff2"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./newsreader/Newsreader72pt-MediumItalic.woff2"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./newsreader/Newsreader72pt-SemiBold.woff2"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./newsreader/Newsreader72pt-SemiBoldItalic.woff2"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./newsreader/Newsreader72pt-Bold.woff2"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./newsreader/Newsreader72pt-BoldItalic.woff2"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./newsreader/Newsreader72pt-ExtraBold.woff2"),
          },
          {
            name: "Extra Bold Italic",
            style: "italic",
            weight: "800",
            url: await import("./newsreader/Newsreader72pt-ExtraBoldItalic.woff2"),
          },
        ],
      },
      cooperHewitt: {
        name: "Cooper Hewitt",
        sizeFactor: 0.95,
        styles: [
          {
            name: "Thin",
            style: "normal",
            weight: "100",
            url: await import("./cooper-hewitt/CooperHewitt-Thin.woff"),
          },
          {
            name: "Thin Italic",
            style: "italic",
            weight: "100",
            url: await import("./cooper-hewitt/CooperHewitt-ThinItalic.woff"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./cooper-hewitt/CooperHewitt-Light.woff"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./cooper-hewitt/CooperHewitt-LightItalic.woff"),
          },
          {
            name: "Book",
            style: "normal",
            weight: "400",
            url: await import("./cooper-hewitt/CooperHewitt-Book.woff"),
          },
          {
            name: "Book Italic",
            style: "italic",
            weight: "400",
            url: await import("./cooper-hewitt/CooperHewitt-BookItalic.woff"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./cooper-hewitt/CooperHewitt-Medium.woff"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./cooper-hewitt/CooperHewitt-MediumItalic.woff"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./cooper-hewitt/CooperHewitt-Semibold.woff"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./cooper-hewitt/CooperHewitt-SemiboldItalic.woff"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./cooper-hewitt/CooperHewitt-Bold.woff"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./cooper-hewitt/CooperHewitt-BoldItalic.woff"),
          },
          {
            name: "Heavy",
            style: "normal",
            weight: "900",
            url: await import("./cooper-hewitt/CooperHewitt-Heavy.woff"),
          },
          {
            name: "Heavy Italic",
            style: "italic",
            weight: "900",
            url: await import("./cooper-hewitt/CooperHewitt-HeavyItalic.woff"),
          },
        ],
      },
      alegreyaSans: {
        name: "Alegreya Sans",
        sizeFactor: 1.05,
        styles: [
          {
            name: "Thin",
            style: "normal",
            weight: "100",
            url: await import("./alegreya-sans/AlegreyaSans-Thin.ttf"),
          },
          {
            name: "Thin Italic",
            style: "italic",
            weight: "100",
            url: await import("./alegreya-sans/AlegreyaSans-ThinItalic.ttf"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./alegreya-sans/AlegreyaSans-Light.ttf"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./alegreya-sans/AlegreyaSans-LightItalic.ttf"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./alegreya-sans/AlegreyaSans-Regular.ttf"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./alegreya-sans/AlegreyaSans-Italic.ttf"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./alegreya-sans/AlegreyaSans-Medium.ttf"),
          },
          {
            name: "Medium Italic",
            style: "italic",
            weight: "500",
            url: await import("./alegreya-sans/AlegreyaSans-MediumItalic.ttf"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./alegreya-sans/AlegreyaSans-Bold.ttf"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./alegreya-sans/AlegreyaSans-BoldItalic.ttf"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./alegreya-sans/AlegreyaSans-ExtraBold.ttf"),
          },
          {
            name: "Extra Bold Italic",
            style: "italic",
            weight: "800",
            url: await import("./alegreya-sans/AlegreyaSans-ExtraBoldItalic.ttf"),
          },
          {
            name: "Black",
            style: "normal",
            weight: "900",
            url: await import("./alegreya-sans/AlegreyaSans-Black.ttf"),
          },
          {
            name: "Black Italic",
            style: "italic",
            weight: "900",
            url: await import("./alegreya-sans/AlegreyaSans-BlackItalic.ttf"),
          },
        ],
      },
      bricolageGrotesque: {
        name: "Bricolage Grotesque",
        sizeFactor: 0.95,
        styles: [
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./bricolage-grotesque/BricolageGrotesque-ExtraLight.ttf"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./bricolage-grotesque/BricolageGrotesque-Light.ttf"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./bricolage-grotesque/BricolageGrotesque-Regular.ttf"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./bricolage-grotesque/BricolageGrotesque-Medium.ttf"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./bricolage-grotesque/BricolageGrotesque-SemiBold.ttf"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./bricolage-grotesque/BricolageGrotesque-Bold.ttf"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./bricolage-grotesque/BricolageGrotesque-ExtraBold.ttf"),
          },
        ],
      },
      bricolageGrotesqueSemiCondensed: {
        name: "Bricolage Grotesque SemiCondensed",
        sizeFactor: 0.95,
        styles: [
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./bricolage-grotesque/BricolageGrotesque_SemiCondensed-ExtraLight.ttf"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./bricolage-grotesque/BricolageGrotesque_SemiCondensed-Light.ttf"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./bricolage-grotesque/BricolageGrotesque_SemiCondensed-Regular.ttf"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./bricolage-grotesque/BricolageGrotesque_SemiCondensed-Medium.ttf"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./bricolage-grotesque/BricolageGrotesque_SemiCondensed-SemiBold.ttf"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./bricolage-grotesque/BricolageGrotesque_SemiCondensed-Bold.ttf"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./bricolage-grotesque/BricolageGrotesque_SemiCondensed-ExtraBold.ttf"),
          },
        ],
      },
      bricolageGrotesqueCondensed: {
        name: "Bricolage Grotesque Condensed",
        sizeFactor: 0.95,
        styles: [
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./bricolage-grotesque/BricolageGrotesque_Condensed-ExtraLight.ttf"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./bricolage-grotesque/BricolageGrotesque_Condensed-Light.ttf"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./bricolage-grotesque/BricolageGrotesque_Condensed-Regular.ttf"),
          },
          {
            name: "Medium",
            style: "normal",
            weight: "500",
            url: await import("./bricolage-grotesque/BricolageGrotesque_Condensed-Medium.ttf"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./bricolage-grotesque/BricolageGrotesque_Condensed-SemiBold.ttf"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./bricolage-grotesque/BricolageGrotesque_Condensed-Bold.ttf"),
          },
          {
            name: "Extra Bold",
            style: "normal",
            weight: "800",
            url: await import("./bricolage-grotesque/BricolageGrotesque_Condensed-ExtraBold.ttf"),
          },
        ],
      },
      titilliumWeb: {
        name: "Titillium Web",
        sizeFactor: 1,
        styles: [
          {
            name: "Extra Light",
            style: "normal",
            weight: "200",
            url: await import("./titillium-web/TitilliumWeb-ExtraLight.ttf"),
          },
          {
            name: "Extra Light Italic",
            style: "italic",
            weight: "200",
            url: await import("./titillium-web/TitilliumWeb-ExtraLightItalic.ttf"),
          },
          {
            name: "Light",
            style: "normal",
            weight: "300",
            url: await import("./titillium-web/TitilliumWeb-Light.ttf"),
          },
          {
            name: "Light Italic",
            style: "italic",
            weight: "300",
            url: await import("./titillium-web/TitilliumWeb-LightItalic.ttf"),
          },
          {
            name: "Regular",
            style: "normal",
            weight: "400",
            url: await import("./titillium-web/TitilliumWeb-Regular.ttf"),
          },
          {
            name: "Regular Italic",
            style: "italic",
            weight: "400",
            url: await import("./titillium-web/TitilliumWeb-Italic.ttf"),
          },
          {
            name: "Semibold",
            style: "normal",
            weight: "600",
            url: await import("./titillium-web/TitilliumWeb-SemiBold.ttf"),
          },
          {
            name: "Semibold Italic",
            style: "italic",
            weight: "600",
            url: await import("./titillium-web/TitilliumWeb-SemiBoldItalic.ttf"),
          },
          {
            name: "Bold",
            style: "normal",
            weight: "700",
            url: await import("./titillium-web/TitilliumWeb-Bold.ttf"),
          },
          {
            name: "Bold Italic",
            style: "italic",
            weight: "700",
            url: await import("./titillium-web/TitilliumWeb-BoldItalic.ttf"),
          },
          {
            name: "Black",
            style: "normal",
            weight: "900",
            url: await import("./titillium-web/TitilliumWeb-Black.ttf"),
          },
        ],
      },
    },
  };
}
