/*
 * Build the app-wide menu based on the current state.
 *  Note: the Window and Help menus are generated by Swift, then injected in. Windows-equivalent menus still need to be added.
 */

import {
  Menu,
  MenuItem,
  PredefinedMenuItem,
  CheckMenuItem,
  Submenu,
} from "@tauri-apps/api/menu";
import { emit } from "@tauri-apps/api/event";
import { platform as getPlatform } from "@tauri-apps/plugin-os";
import { setMenu } from "./setMenu";
import { WindowType } from "../typings";

export async function buildMenu(windowType: WindowType) {
  const platform = getPlatform();

  /*
   * App menu
   */
  const appSubmenu = await Submenu.new({
    text: "Choicelab",
    id: "app_submenu",
    items: [
      await MenuItem.new({
        id: "about",
        text: "About Choicelab",
        enabled: false,
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await PredefinedMenuItem.new({
        item: "Services",
      }),
      await PredefinedMenuItem.new({
        text: "",
        item: "Separator",
      }),
      await PredefinedMenuItem.new({
        text: "Hide Choicelab",
        item: "Hide",
      }),
      await PredefinedMenuItem.new({
        item: "HideOthers",
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await MenuItem.new({
        id: "request-quit",
        text: "Quit Choicelab",
        accelerator: "CmdOrCtrl+Q",
      }),
    ],
  });

  /*
   * File menu
   */

  const fileSubmenu = await Submenu.new({
    text: "File",
    id: "file_submenu",
    items: [
      await MenuItem.new({
        id: "new_project",
        text: "New...",
        accelerator: "CmdOrCtrl+Shift+N",
      }),
      await MenuItem.new({
        id: "open_project",
        text: "Open...",
        accelerator: "CmdOrCtrl+O",
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await MenuItem.new({
        text: "Save",
        id: "save",
        accelerator: "CmdOrCtrl+S",
        enabled: false,
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await MenuItem.new({
        text: "Export for Web...",
        id: "export",
        accelerator: "CmdOrCtrl+E",
        enabled: false,
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await PredefinedMenuItem.new({
        text: "Close Window",
        item: "CloseWindow",
      }),
    ],
  });

  /*
   * Edit menu
   */

  const editSubmenu = await Submenu.new({
    text: "Edit",
    id: "edit_submenu",
    items: [
      await MenuItem.new({
        text: "Undo",
        id: "undo",
        accelerator: "CmdOrCtrl+Z",
        enabled: false,
      }),
      await MenuItem.new({
        text: "Redo",
        id: "redo",
        accelerator: "CmdOrCtrl+Shift+Z",
        enabled: false,
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await PredefinedMenuItem.new({
        item: "Cut",
      }),
      await PredefinedMenuItem.new({
        item: "Copy",
      }),
      await PredefinedMenuItem.new({
        item: "Paste",
      }),
      await PredefinedMenuItem.new({
        item: "SelectAll",
      }),
    ],
  });

  /*
   * View menu
   */

  const viewSubmenu = await Submenu.new({
    text: "View",
    id: "view_submenu",
    items: [
      await CheckMenuItem.new({
        id: "show_node_editor",
        text: "Show Node Editor",
        enabled: false,
        accelerator: "CmdOrCtrl+E",
      }),
      await CheckMenuItem.new({
        id: "show_variables",
        text: "Show Variables",
        enabled: false,
        accelerator: "CmdOrCtrl+R",
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await MenuItem.new({
        id: "toggle_preview",
        text: "Toggle Preview",
        accelerator: "CmdOrCtrl+G",
        enabled: false,
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
    ],
  });

  /*
   * Project menu
   */

  const projectSubmenu = await Submenu.new({
    text: "Project",
    id: "project_submenu",
    items: [
      await MenuItem.new({
        id: "new_cell",
        text: "New Cell",
        enabled: false,
        accelerator: "CmdOrCtrl+N",
      }),
      await MenuItem.new({
        id: "new_branch",
        text: "New Branch",
        enabled: false,
        accelerator: "CmdOrCtrl+B",
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await MenuItem.new({
        id: "set_link",
        text: "Set Link",
        enabled: false,
        accelerator: "CmdOrCtrl+L",
      }),
      await MenuItem.new({
        id: "disconnect_link",
        text: "Disconnect Link",
        enabled: false,
        accelerator: "CmdOrCtrl+D",
      }),
      await MenuItem.new({
        id: "autofill",
        text: "Autofill Variables",
        enabled: false,
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await MenuItem.new({
        id: "open_in_browser",
        text: "Open Preview in Browser",
        enabled: false,
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await MenuItem.new({
        id: "delete_nodes",
        text: "Delete Node",
        enabled: false,
        accelerator: "CmdOrCtrl+Delete",
      }),
      await MenuItem.new({
        id: "delete_stem",
        text: "Delete Branch Stem",
        enabled: false,
        accelerator: "CmdOrCtrl+Option+Delete",
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await MenuItem.new({
        id: "project_settings",
        text: "Project Settings...",
        enabled: false,
        accelerator: "CmdOrControl+Shift+,",
      }),
    ],
  });

  /*
   * Window submenu, to be handled by Tauri once functionality is available (see below)
   *
  const windowSubmenu = await Submenu.new({
    text: "Window",
    id: "window_submenu",
  });
  */

  const helpSubmenu = await Submenu.new({
    text: "Help",
    id: "help_submenu",
    items: [
      await MenuItem.new({
        id: "report_issue",
        text: "Report Issue or Request Feature...",
      }),
      await MenuItem.new({
        id: "open_whatsNew",
        text: "Release Notes",
      }),
    ],
  });

  /*
   * Set the menu
   */
  let menu = null;
  switch (platform) {
    case "windows":
    case "linux":
      // On Windows and Linux, only show the menu in project windows
      if (windowType === "project") {
        const items = [
          fileSubmenu,
          editSubmenu,
          viewSubmenu,
          projectSubmenu,
          helpSubmenu,
        ];
        menu = await Menu.new({ items: items });
        menu.setAsWindowMenu();
      }
      break;
    case "macos":
      const items = [
        appSubmenu,
        fileSubmenu,
        editSubmenu,
        viewSubmenu,
        projectSubmenu,
        // windowSubmenu,
        // helpSubmenu,
      ];
      menu = await Menu.new({ items: items });
      // await windowSubmenu.setAsWindowsMenuForNSApp();
      // await helpSubmenu.setAsHelpMenuForNSApp();
      menu.setAsAppMenu();
      emit("add-native-menus");
      break;
  }
  if (menu === null) return;
  setMenu(windowType);
}
