/*
 * Build the app-wide menu based on the current state.
 *  Note: the Window and Help menus are generated by Swift, then injected in. Windows-equivalent menus still need to be added.
 */

import {
  Menu,
  MenuItem,
  PredefinedMenuItem,
  CheckMenuItem,
  Submenu,
} from "@tauri-apps/api/menu";
import { getCurrentWebviewWindow } from "@tauri-apps/api/webviewWindow";
import showPane from "../editor/inspector/functions/showPane";
import { createCell, createBranch } from "../data/createNode";
import insertNewNode from "../editor/flowchart/general/insertNewNode";
import { emit } from "@tauri-apps/api/event";
import { platform as getPlatform } from "@tauri-apps/plugin-os";
import enterTargetMode from "../editor/flowchart/target-mode/enterTargetMode";
import handleDisconnectLinks from "../editor/flowchart/general/handleDisconnectLinks";
import { handleDeleteNodes } from "../editor/flowchart/general/handleDelete";
import { getStemParent } from "../data/getData";
import { Branch, WindowType } from "../typings";
import { handleDeleteStem } from "../editor/flowchart/general/handleDelete";
import { togglePreview } from "../preview/togglePreview";
import { openProjectSettings } from "../editor/settings/openProjectSettings";
import { open } from "@tauri-apps/plugin-shell";
import { saveProject } from "../fs/saveProject";
import openProject from "../fs/openProject";
import newProject from "../fs/newProject";
import { getStore, getViewStore } from "../data/dataStore";
import { setMenu } from "./setMenu";

const appWindow = getCurrentWebviewWindow();

export async function buildMenu(windowType: WindowType) {
  const fns = window.__CHOICELAB_FUNCTIONS__;
  const update = fns.updateProject;
  const viewStore = getViewStore();
  const platform = getPlatform();
  const isProjectState = windowType === "project" ? true : false;

  /*
   * App menu
   */
  const aboutItem = await MenuItem.new({
    id: "about",
    text: "About Choicelab",
    enabled: false,
    action: () => {},
  });
  let quit = await MenuItem.new({
    id: "request-quit",
    text: "Quit Choicelab",
    accelerator: "CmdOrCtrl+Q",
    action: () => {
      /* Emit a request to quit, responded to in MainEditor
       */
      emit("menu-request-quit");
      /*
     SIDE NOTE: There's an argument to be made that some of the `action` props in other menu items in this function could do the same thing, just emit requests, and put the function body wherever else it's best suited. (Stuff that calls the main React `update` handler, in particular.) But until setMenu gets too unwieldy, this approach is fine.
     */
    },
  });
  const appSubmenu = await Submenu.new({
    text: "Choicelab",
    id: "app_submenu",
    items: [
      aboutItem,
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await PredefinedMenuItem.new({
        item: "Services",
      }),
      await PredefinedMenuItem.new({
        text: "",
        item: "Separator",
      }),
      await PredefinedMenuItem.new({
        text: "Hide Choicelab",
        item: "Hide",
      }),
      await PredefinedMenuItem.new({
        item: "HideOthers",
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      quit,
    ],
  });

  /*
   * File menu
   */

  const save = await MenuItem.new({
    text: "Save",
    accelerator: "CmdOrCtrl+S",
    enabled: false,
    action: () => {
      saveProject();
    },
  });

  const fileSubmenu = await Submenu.new({
    text: "File",
    id: "file_submenu",
    items: [
      await MenuItem.new({
        id: "new_project",
        text: "New...",
        accelerator: "CmdOrCtrl+Shift+N",
        action: () => {
          const source =
            windowType === "project" || windowType === "projectSettings"
              ? viewStore.projectPath
              : windowType;
          newProject(source);
        },
      }),
      await MenuItem.new({
        id: "open_project",
        text: "Open...",
        accelerator: "CmdOrCtrl+O",
        action: () => {
          openProject();
        },
      }),
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      save,
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await PredefinedMenuItem.new({
        text: "Close Window",
        item: "CloseWindow",
      }),
    ],
  });

  /*
   * Edit menu
   */

  // Undo
  let undo = await MenuItem.new({
    text: "Undo",
    accelerator: "CmdOrCtrl+Z",
    enabled: false,
  });

  // Redo
  let redo = await MenuItem.new({
    text: "Redo",
    accelerator: "CmdOrCtrl+Shift+Z",
    enabled: false,
  });

  const editSubmenu = await Submenu.new({
    text: "Edit",
    id: "edit_submenu",
    items: [
      undo,
      redo,
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      await PredefinedMenuItem.new({
        item: "Cut",
      }),
      await PredefinedMenuItem.new({
        item: "Copy",
      }),
      await PredefinedMenuItem.new({
        item: "Paste",
      }),
      await PredefinedMenuItem.new({
        item: "SelectAll",
      }),
    ],
  });

  /*
   * View menu
   */

  const showNodeEditor = await CheckMenuItem.new({
    id: "show_node_editor",
    text: "Show Node Editor",
    enabled: false,
    accelerator: "CmdOrCtrl+E",
    action: async () => {
      const focused = await appWindow.isFocused();
      if (focused === false) return;
      showPane("node-editor", update);
    },
  });

  const showVariables = await CheckMenuItem.new({
    id: "show_variables",
    text: "Show Variables",
    enabled: false,
    accelerator: "CmdOrCtrl+R",
    action: async () => {
      const focused = await appWindow.isFocused();
      if (focused === false) return;
      showPane("variables", update);
    },
  });

  const togglePreviewItem = await MenuItem.new({
    id: "toggle_preview",
    text: "Toggle Preview",
    accelerator: "CmdOrCtrl+G",
    enabled: false,
    action: async () => {
      const focused = await appWindow.isFocused();
      if (focused === false) return;
      togglePreview(update);
    },
  });

  const viewSubmenu = await Submenu.new({
    text: "View",
    id: "view_submenu",
    items: [
      showNodeEditor,
      showVariables,
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      togglePreviewItem,
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
    ],
  });

  /*
   * Project menu
   */

  const newCell = await MenuItem.new({
    id: "new_cell",
    text: "New Cell",
    enabled: false,
    accelerator: "CmdOrCtrl+N",
    action: async () => {
      const focused = await appWindow.isFocused();
      if (focused === false) return;
      const newCell = createCell();
      insertNewNode(newCell, update);
    },
  });

  const newBranch = await MenuItem.new({
    id: "new_branch",
    text: "New Branch",
    enabled: false,
    accelerator: "CmdOrCtrl+B",
    action: async () => {
      const focused = await appWindow.isFocused();
      if (focused === false) return;
      const newBranch = createBranch();
      insertNewNode(newBranch, update);
    },
  });

  const setLink = await MenuItem.new({
    id: "set_link",
    text: "Set Link",
    enabled: false,
    accelerator: "CmdOrCtrl+L",
    action: async () => {
      const focused = await appWindow.isFocused();
      if (focused === false) return;
      enterTargetMode({
        update: update,
      });
    },
  });
  const disconnectLink = await MenuItem.new({
    id: "disconnect_link",
    text: "Disconnect Link",
    enabled: false,
    accelerator: "CmdOrCtrl+D",
    action: async () => {
      const focused = await appWindow.isFocused();
      if (focused === false) return;
      handleDisconnectLinks(update);
    },
  });

  const deleteNodes = await MenuItem.new({
    id: "delete_nodes",
    text: "Delete Node",
    enabled: false,
    accelerator: "CmdOrCtrl+Delete",
    action: async () => {
      const focused = await appWindow.isFocused();
      if (focused === false) return;
      handleDeleteNodes(update);
    },
  });

  const deleteStem = await MenuItem.new({
    id: "delete_stem",
    text: "Delete Branch Stem",
    enabled: false,
    accelerator: "CmdOrCtrl+Option+Delete",
    action: async () => {
      const focused = await appWindow.isFocused();
      if (focused === false) return;
      const store = getStore();
      const selectedStem = viewStore.selectedStem;
      if (selectedStem !== false) {
        const parentBranch: Branch | undefined = getStemParent(
          selectedStem.id,
          store,
        );
        if (parentBranch && selectedStem.type !== "noMatch") {
          handleDeleteStem(selectedStem.id, parentBranch.id, update);
        }
      }
    },
  });

  const previewInBrowser = await MenuItem.new({
    id: "open_in_browser",
    text: "Open Preview in Browser",
    enabled: false,
    action: async () => {
      const port = getViewStore().previewPort;
      await open(`http://localhost:${port}`);
    },
  });

  const projectSettings = await MenuItem.new({
    id: "project_settings",
    text: "Project Settings...",
    enabled: false,
    accelerator: "CmdOrControl+Shift+,",
    action: () => {
      openProjectSettings();
    },
  });

  const projectSubmenu = await Submenu.new({
    text: "Project",
    id: "project_submenu",
    items: [
      newCell,
      newBranch,
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      setLink,
      disconnectLink,
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      previewInBrowser,
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      deleteNodes,
      deleteStem,
      await PredefinedMenuItem.new({
        item: "Separator",
      }),
      projectSettings,
    ],
  });

  const windowSubmenu = await Submenu.new({
    text: "Window",
    id: "window_submenu",
    items: [],
  });

  const helpSubmenu = await Submenu.new({
    text: "Help",
    id: "help_submenu",
    items: [
      await MenuItem.new({
        id: "report_issue",
        text: "Report Issue or Request Feature...",
        action: async () => {
          const url =
            "https://docs.google.com/forms/d/e/1FAIpQLSdXVX91Ze0jAmu9FOaqEvMv-VxYFPYOeQVcuQt9YdShwSSXKQ/viewform?usp=sf_link";
          await open(url);
        },
      }),
    ],
  });

  /*
   * Set the menu
   */
  let menu = null;
  switch (platform) {
    case "windows":
    case "linux":
      // On Windows and Linux, only show the menu in project windows
      if (isProjectState) {
        const items = [
          fileSubmenu,
          editSubmenu,
          viewSubmenu,
          projectSubmenu,
          helpSubmenu,
        ];
        menu = await Menu.new({ items: items });
        menu.setAsWindowMenu();
      }
      break;
    case "macos":
      windowSubmenu.setAsWindowsMenuForNSApp();
      helpSubmenu.setAsHelpMenuForNSApp();
      const items = [
        appSubmenu,
        fileSubmenu,
        editSubmenu,
        viewSubmenu,
        projectSubmenu,
        windowSubmenu,
        helpSubmenu,
      ];
      menu = await Menu.new({ items: items });
      // On macOS, show the menu in all windows
      menu.setAsAppMenu();
      break;
  }
  if (menu === null) return;
  fns.menus[windowType] = menu;
  setMenu(windowType);
}
